title: Alyssa Hwang
author:
  name: Alyssa Hwang
  email: ahwang16@seas.upenn.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Alyssa Hwang is a PhD student at the University of Pennsylvania advised by
  Andrew Head and Chris Callison-Burch. She works on AI assistants that help 
  users manage many details at once.
show_excerpts: false # set to true to show excerpts on the homepage
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github: ahwang16
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - CV.md
  - projects.md
  - icons.md
  - advice.md

# Build settings
theme: minima

permalink: /:collection/:categories/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-seo-tag
